// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkcreMS9pdKN7suE_dvw6Xd0RJPJjAR_g',
    appId: '1:923098663948:web:0f2055262964e12ab1b229',
    messagingSenderId: '923098663948',
    projectId: 'ca202-7fbae',
    authDomain: 'ca202-7fbae.firebaseapp.com',
    storageBucket: 'ca202-7fbae.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcHRKOLrOVJ_xY8cXdGjV6djYiqeIsCkw',
    appId: '1:923098663948:android:96f6012671936a0db1b229',
    messagingSenderId: '923098663948',
    projectId: 'ca202-7fbae',
    storageBucket: 'ca202-7fbae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzhengb5t6LvVO2uz5d7VhzH6xLMp-bE0',
    appId: '1:923098663948:ios:0cb24f9ab3d7e9b8b1b229',
    messagingSenderId: '923098663948',
    projectId: 'ca202-7fbae',
    storageBucket: 'ca202-7fbae.appspot.com',
    iosBundleId: 'com.example.ca202Ch6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzhengb5t6LvVO2uz5d7VhzH6xLMp-bE0',
    appId: '1:923098663948:ios:e4c81412f4de84dcb1b229',
    messagingSenderId: '923098663948',
    projectId: 'ca202-7fbae',
    storageBucket: 'ca202-7fbae.appspot.com',
    iosBundleId: 'com.example.ca202Ch6.RunnerTests',
  );
}
